module.exports = {
  apps: [
    {
      name: "bananavision-backend",
      cwd: "/home/project/bananavisionv3/backend",
      script: "server.js",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "development",
        PORT: 5000,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 5000,
        TRUST_PROXY: "1",
      },
      watch: false,
      max_memory_restart: "500M",
      restart_delay: 3000,
      max_restarts: 10,
      out_file: "/home/project/bananavisionv3/logs/backend-out.log",
      error_file: "/home/project/bananavisionv3/logs/backend-err.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "bananavision-python",
      cwd: "/home/project/bananavisionv3/python",
      script: "server.py",
      interpreter: "/home/project/bananavisionv3/venv/bin/python",
      args: "",
      instances: 1,
      exec_mode: "fork",
      env: {
        MODEL_TYPE: "mobilenetv2",
        MODEL_DIR: "/home/project/bananavisionv3/models",
        NODE_BACKEND_URL: "http://localhost:5000/api",
      },
      env_production: {
        MODEL_TYPE: "mobilenetv2",
        MODEL_DIR: "/home/project/bananavisionv3/models",
        NODE_BACKEND_URL: "http://localhost:5000/api",
      },
      watch: false,
      max_memory_restart: "3G",
      restart_delay: 5000,
      max_restarts: 5,
      out_file: "/home/project/bananavisionv3/logs/python-out.log",
      error_file: "/home/project/bananavisionv3/logs/python-err.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
